### ISSUE TITLE
Database design and interface

### ISSUE THREAD

**Issue by mxsasha** [irrdnet/irrd#11]
This task involves building a basic database design, and implementing it, probably with an ORM, probably SQLAlchemy. (The interface between the database layer and other parts of IRRD should obviously be ORM-agnostic). In design, we need to account for issues like the references between objects, and the various methods of searching by resource or lookup keys. We only need to consider PostgreSQL.

**Comment by mahtin** [comment]
@mxsasha - Your "We only need to consider PostgreSQL" is, I hope, said in jest. While I can be a fan of one database or another, I would not be a fan of such a singular statement.

As I said, I hope you said that in jest and expect code to work independent of database engine.
