### ISSUE TITLE
Implement NRTM v4

### ISSUE THREAD

**Issue by job** [irrdnet/irrd#121]
Depends on #91 

Whatever RRDP variant is specified for NRTM v4 should be implemented in IRRd v4

**Comment by mxsasha** [comment]
Work on specifying NRTMv4 is started in https://github.com/mxsasha/nrtmv4/
Funding has also been arranged for this implementation task.

**Comment by mxsasha** [comment]
#857 and #890 have implemented NRTMv4 🎉 
(unless we change it)
