### ISSUE TITLE
Redesign authentication (stop doing traditional RPSL and separate data / auth)

### ISSUE THREAD

**Issue by job** [irrdnet/irrd#122]
Authentication methods should move out of the `mntner` object and into a separate datastore that is not publicly queryable like the normal RPSL data.

We'd want to encourage the use of per application API keys, and perhaps a SSO or OAUTH concept to represent individual users or groups of users.

**Comment by job** [comment]
Split this out:

* authentication portal designed for humans
* humans must create an account in the portal (username, password, TOTP)
* human migrates the `mntner` authentication methods to the new system by once proving they know one of the authentication methods, and by clicking a confirm email send to the `admin-c` of the `mntner` object

after the migration: humans can add/remove other humans, add/remove API keys, add(?)/remove legacy authentication methods such as GPG and CRYPT/MD5

API keys have 2 permission levels ('modify objects', and 'modify authentication list').

**Comment by job** [comment]
It should be possible to restrict API keys to source IP address blocks (default is `0.0.0.0/0` and `::/0`)

**Comment by job** [comment]
perhaps for a new ticket: it should be possible to see/query for the authentication log associated with a `mntner` and see which humans and which API keys have done what actions from what source IP addresses at what timestamp

**Comment by mxsasha** [comment]
Closing in favour of #617
