### ISSUE TITLE
Allow to query for objects via HTTPS API

### ISSUE THREAD

**Issue by job** [irrdnet/irrd#123]
* All port 43 queries (such as `!i`) must have an equivalent in the HTTPS API
* HTTP query pipelining or multiplexing must be available to make things fast enough

Small queries can be a `GET`, complex queries which have lengthy parameters will probably be `POST`.

For all `RADB` and `RIPE` queries we must build a table and de-duplicate between them.

Overall goal is to be able to interact with IRRd without having to use any whois commands on `port 43`

**Comment by job** [comment]
Two types of queries: 'simple' queries which search for objects, and "Server Sided Processing" (SSP) queries, an example of the former is `165.254.255.0` and the latter is `!iAS15562`.

For simple queries we want plaintext output, and XML output. In plaintext output you basically get back in the HTTP response body what you'd get back on port 43, the XML output the objects' attributes are split out into different elements.

For SSP queries will only output structured data (format TBD)

**Comment by devicenull** [comment]
We'd love to see this, writing code that interacts with the whois API in a reliable fashion is pretty annoying to do.  Consider JSON instead of XML though (way easier to work with).

**Comment by forkwhilefork** [comment]
I'd also like to register my interest. This would be really big for me for integration into other systems.

**Comment by christheradioguy** [comment]
* raises hand*  I would also love to see this feature implemented.  Right now for integration I'm torn between querying the postgresql database directly or writing a whois client, an http(s) API would be fantastic.

**Comment by mxsasha** [comment]
@christheradioguy @forkwhilefork @devicenull @job - as you've expressed previous interest in an IRRd HTTP API: we've started implementation of an HTTP interface based on GraphQL, and an experimental version is now available, see https://github.com/irrdnet/irrd/pull/398#issuecomment-699668156
