### ISSUE TITLE
Mirroring: initial database import

### ISSUE THREAD

**Issue by mxsasha** [irrdnet/irrd#14]
For NRTM mirroring, load the initial copy of the database over http(s)/ftp, and load it into the database (replacing existing objects from the same source). The serial should also be retrieved and recorded.

This should be based on a basic configuration which includes the ability to filter for certain object types.

**Comment by job** [comment]
Also ability to load from local files.

Sometimes there make note be a CURRENTSERIAL file. Let’s make a note that
some “autoincrement” feature is added for convenience.
