### ISSUE TITLE
RPKI Origin Validation in context of IRR

### ISSUE THREAD

**Issue by job** [irrdnet/irrd#197]
Allow a new type of data (RPKI ROAs) to 'drown out' IRR data sources. The goal is to have RPKI data supersede IRR data. By using RPKI data we can combat stale or fraudulent IRR proxy route registrations.

Consider the following:

```
$ whois -h mockup 192.0.2.0
route: 192.0.2.0/24
origin: AS1
source: NTTCOM

route: 192.0.2.0/25
origin: AS2
source: NTTCOM

roa: 192.0.2.0/24
maxlength: 24
origin: AS2
source: RPKI # RIPE TAL
```

What I'd like to see is that `!gAS1` (or `!aAS1`) will _not_ return `192.0.2.0/24 192.0.2.0/25` because of the existence of the RPKI ROA entry covering `192.0.2.0/24 maxlen 24`.

The `192.0.2.0/24AS1` entry is hidden because it conflicts with the `roa:` entry, or phrased differently because there is no roa that permits that origin for that prefix. The procedure to validate `route:` objects against RPKI ROAs can be taken from RFC 6811 section 2.

The RPKI ROA database is encoded in a JSON file and can be downloaded (for example) from https://rpki.gin.ntt.net/api/export.json, this table is expected to refresh every 20 minutes.

A new data type in the IRRd data model should introduces, the 'roa'.

From the downloaded RPKI ROA data an IRR-like source should be synthesised. `!g`, `!a` etc should return routes like `route:` objects would. The synthesised RPKI source should be enabled by default.

The RPKI Origin Validation process should be applied on all the entry points: NRTM, submissions to authoritative, or dump loads. If a `route:` object is encountered that conflicts with all ROAs it should be marked as 'invalid'.

All (or a cleverly decided subset) `route:` objects must be re-validated when `export.json` contains new roas or roas are deleted.

**Comment by mahtin** [comment]
Can’t ...

All (or a cleverly decided subset) route: objects must be re-validated when export.json contains new roas or roas are deleted.

... be done at route query time?

**Comment by mxsasha** [comment]
@job is there any documentation of the JSON export format, or a definition/RFC? It looks unambiguous  to me from what I've seen, but it would be good to know about any "surprise features" that may occur, if any.


> Can’t ...
> 
> All (or a cleverly decided subset) route: objects must be re-validated when export.json contains new roas or roas are deleted.
> 
> ... be done at route query time?

That is a possibility, but I would be concerned about query performance. Whether that would be impacted, and what the optimal place is, can be decided once more design work has been done.

**Comment by job** [comment]
@mxsasha there is no formal specification of that JSON format. Both routinator and the ripe ncc validator support it though.

**Comment by job** [comment]
I wrote a small tool to demonstrate the idea: https://github.com/job/ripe-proposal-2018-06

Additional feature aspect: it should be possible to disable the RPKI based Origin Validation per database. In the case of NTT there is the `INTERNAL` database which will contain "invalids", for internal purposes.

**Comment by mxsasha** [comment]
Thanks for the link to the tool. That's also helpful in cross-checking my code.

Comparing RIPE-NONAUTH, there are 38 route objects that my current (non-public) code considers invalid, but yours considers valid:
```
2C0F:F530:10::/44AS60211
2C0F:FB18::/32AS29606
2C0F:FB18::/32AS30844
69.169.224.0/22AS201341
69.169.228.0/22AS201341
103.102.6.0/23AS131477
103.194.168.0/22AS133229
103.86.68.0/22AS131477
111.119.160.0/21AS38193
111.119.160.0/22AS38193
111.119.164.0/22AS38193
111.119.168.0/21AS38193
118.103.224.0/20AS38193
119.73.32.0/19AS38193
122.129.64.0/19AS38193
124.108.22.0/23AS393960
161.129.36.0/23AS131477
202.69.8.0/21AS38193
203.170.64.0/20AS38193
203.80.128.0/23AS38193
203.80.130.0/23AS38193
216.137.56.0/23AS39111
216.137.58.0/23AS39111
216.137.62.0/23AS39111
2001:13C7:6004::/64AS28017
2001:200:1BA::/48AS24047
2001:4498:4::/48AS24218
2001:504:3D::/48AS62972
2402:9E80:14::/48AS132369
2402:9E80:15::/48AS206981
2404:E400:E000::/40AS45345
2404:E400:E400::/40AS45345
2602:FECE:30::/44AS203664
2620:0:1000::/40AS36384
2620:0:1000::/40AS41264
2620:0:1070::/48AS41264
2620:0:862::/48AS43821
2620:95:8000::/48AS54145
```

Looking at `2620:0:1000::/40AS36384`, I only see ROAs for AS15169 and AS45566 on https://rpki.gin.ntt.net/roas (searching for `2620:0:1000::`). I also don't see this prefix among the ROAs looking for `AS36384`. So, at least for this one, it looks like a bug in your tool?

**Comment by job** [comment]
On Fri, Mar 08, 2019 at 05:38:23AM -0800, Sasha Romijn wrote:
> Looking at `2620:0:1000::/40AS36384`, I only see ROAs for AS15169 and
> AS45566 on https://rpki.gin.ntt.net/roas (searching for
> `2620:0:1000::`). I also don't see this prefix among the ROAs looking
> for `AS36384`. So, at least for this one, it looks like a bug in your
> tool?

Yes, smells like a bug. I will research. Thank you for the comparison.
