### ISSUE TITLE
Updates: submission via TCP socket

### ISSUE THREAD

**Issue by mxsasha** [irrdnet/irrd#23]
Provide a TCP interface to IRRd for submitting updates, with further processing as built in #20. This has some overlap with #16.

**Comment by mxsasha** [comment]
@job I've seen this mentioned in the documentation, but am missing a detail on the implementation. 

As far as I understand, the user connects to a TCP socket, enters some objects, maybe a password, same as the content of an e-mail (but without email headers).

How does IRRD know when to input is complete? Is there some "this is the end, please process" marker? Is it based on no new input being sent for a second? Or something else? Or does processing of a single object just start upon encountering an empty line? The latter case means you can't create mutually dependent objects in this way, e.g. a person and mntner that refer to each other.

**Comment by job** [comment]
I think this is the magic not really documented stuff on port 43 that is used when you pipe email into the IRRd.

I think you can skip implementing this feature if you have an "email submission tool" that talks to an API or writes directly into the database.

**Comment by job** [comment]
I think this is the protocol as handled in `programs/irrd_ops/irrd_ops.c` - do you agree? Are we talking about the same thing?

**Comment by mxsasha** [comment]
Yes, looks like that's it. We won't need it then, as we won't keep the current architecture of irr_rpsl_submit.
