### ISSUE TITLE
Retry on DB Timeout

### ISSUE THREAD

**Issue by spolack** [irrdnet/irrd#273]
**Is your feature request related to a problem? Please describe.**
In a "cloud" native environment, pods will come and go. In case of a DB Handover during Query the request is failing.

**Describe the solution you'd like**
Make application more robust by introducing a retry feature.

**Comment by job** [comment]
Are you sure this is happening? When I shut down the PostgreSQL server the IRRd stops replying to queries and logs errors, when I start the PostreSQL daemon again, the IRRd resumes normal operation. This behavior seems compatible with DB handovers.

I guess our operational assumption is that *WHOIS* clients will retry at a later point, not that the IRRd daemon retries the database queries while holding the connection with the whois client open.

Do you have a specific code patch in mind?

**Comment by spolack** [comment]
Hello,

it turned out our database backend was very fragile. Therefore this is not any issue anymore and i can only recommend to fix issues at the root.
