### ISSUE TITLE
Document CONTRIBUTING guidelines

### ISSUE THREAD

**Issue by job** [irrdnet/irrd#277]
We should document guidelines for how to contribute to this project, specifically what we expect from pull-requests:

- license: new code must be made available under the MIT, BSD, or ISC, or an otherwise compatible open source license
- coverage: the pull request must not lower the coverage unless reasonably and specifically documented as to why
- documentation: PRs introducing new features without documenting those new features are problematic
- unit tests / regression tests: new features must be accompanied with proper tests
- merging PRs against irrdnet/irrd requires sign-off from @job or @mxsasha

**Comment by kkirsche** [comment]
I'd recommend also highlighting where you are interested in contributions or good areas for new contributors.
