### ISSUE TITLE
ujson-1.35 with gcc-9.2.0 results in "undefined symbol: Buffer_AppendShortHexUnchecked"

### ISSUE THREAD

**Issue by ccaputo** [irrdnet/irrd#283]
ujson-1.35 in PyPi (currently in requirements.txt & setup.py, and unfortunately the present latest release) is broken with later gcc's such as gcc-9.2.0.  A run of "irrd_database_upgrade" will result in:

```
ImportError: /home/irrd/irrd-venv/lib/python3.6/site-packages/ujson.cpython-36m-x86_64-linux-gnu.so: undefined symbol: Buffer_AppendShortHexUnchecked
```

This work-around (using current head, but specifying the commit in case head breaks) fixes the problem:

```
/home/irrd/irrd-venv/bin/pip3 install git+git://github.com/esnme/ultrajson.git@9722b1aa11f6b33050fddfcdee18e028d19f90de
```

ujson-1.35 is 4 years old but below are some efforts to revive it.  In the meantime, it might be worth updating setup.py & requirements.txt to reference a tested GitHub release such as the above.

Some references to the issue:

https://github.com/pypa/pypi-support/issues/205
https://github.com/esnme/ultrajson/issues/343
https://github.com/esnme/ultrajson/issues/346
https://github.com/esnme/ultrajson/issues/326

**Comment by mxsasha** [comment]
I think we can include this whenever we make the next IRRd release. But if we're lucky, by then the ujson project is revived with a new release.

From some quick googling it seems ujson is still the fastest option, and json decoding performance has a significant impact for some IRRd queries, so sticking to ujson would be best, if possible.

**Comment by mxsasha** [comment]
A new release of ujson was made, and #289 updates the IRRd dependency. So this is fixed in the next IRRd release.
