### ISSUE TITLE
whois blank line continuation format violates rfc2622 

### ISSUE THREAD

**Issue by haussli** [irrdnet/irrd#298]
iird4 pgp key, note the + blank line indicator:

```
key-cert:       PGPKEY-8FF9A87D
method:         PGP
owner:         <foo@bar.com>
fingerpr:       C512 0702 3C18 A0B9 17D7  6B57 31D9 AAFA 8FF9 A873
certif:           -----BEGIN PGP PUBLIC KEY BLOCK-----
                    Version: GnuPG v1.4.5 (GNU/Linux)
<indenting WS>
+                  mQINBFVJAtUBEAC8tcxyfqQAfn1Ba1W3KKiWJTpw+F1yeLkzGQu57ZEsZSphy4K4
   ......
```
irrd2 pgp key:

```
key-cert:   PGPKEY-8FF9A87D
method:     PGP
owner:      <foo@bar.com>
fingerpr:   C512 0702 3C18 A0B9 17D7  6B57 31D9 AAFA 8FF9 A873
certif:
 -----BEGIN PGP PUBLIC KEY BLOCK-----
 Version: GnuPG v1.4.5 (GNU/Linux)
+
 mQINBFVJAtUBEAC8tcxyfqQAfn1Ba1W3KKiWJTpw+F1yeLkzGQu57ZEsZSphy4K4
```

rfc 2622: page 6:
```
   An attribute's value can be split over multiple lines, by having a
   space, a tab or a plus ('+') character as the first character of the
   continuation lines.  The character "+" for line continuation allows
   attribute values to contain blank lines. 
```

The blank line should be continued with a leading '+' on a line by itself, as irrd2 performs it, rather than the indenting whitespace that is there.  While the '+' in its current location, leading the first line of the ascii representation of the key, does not break the formatting, it is unnecessary because of the whitespace that follows it.

FWIW, database exports appear to be doing this line continuation formatting correctly.

**Comment by job** [comment]
this information is retrieved via a `whois` query, right?

**Comment by troy2914** [comment]
Yes,  and note ripe software adds + to all lines. of the certif.

**Comment by mxsasha** [comment]
I'll look into this.
