### ISSUE TITLE
separate log "facilities" into multiple files

### ISSUE THREAD

**Issue by haussli** [irrdnet/irrd#299]
The logging, while useful, is volumous!  Multiple gigabytes are produced each day.  It is difficult to watch or search for a particular event.

It would be useful if logs could be separated in multiple destinations.  For example, mail processing,
NRTM, and queries.  Maybe additional "facilities" (in syslog parlance) would also be useful; these were just off the cuff.

Or, if the logging format were more consistent, regexes in the config file might be specified to direct logs to a destination.  This seems like over-kill.

**Comment by mxsasha** [comment]
This seems reasonable. In fact, Python's logging framework, that IRRd uses, already supports these kind of things. The configuration file exposes only a very small part of it.

There may be some limitations regarding live reloading of the logging configuration. I'll look into that.

**Comment by job** [comment]
Thanks!

**Comment by mxsasha** [comment]
This is fixed in 458b49251d9bd3bc765b65bfc8825a5dd78f2811. It allows setting a custom Python logging configuration, which is incredibly flexible.
