### ISSUE TITLE
SLURM support in RPKI

### ISSUE THREAD

**Issue by job** [irrdnet/irrd#302]
SLURM (RFC 8416) is a standardized JSON format to describe "local" (in this case IRRd instance specific) exceptions to the RPKI Origin Validation process.

From section 3.2 we need support for `validationOutputFilters.prefixFilters` and `locallyAddedAssertions.prefixAssertions` (so the BGPSec stuff can just be ignored entirely).

In the IRRd configuration we should be able to point at a SLURM file hosted on the local filesystem or on a HTTPS url. The IRRd should periodically refresh the SLURM file (every 10 minutes?), and also reload it at SIGHUP.

What `prefixFilters` does is simple pruning of the VRPs in the JSON ROA file: if there is a VRP covered by a prefix in the `prefixFilters`, the VRP is ignored. As if it was deleted from the JSON file. What `prefixAssertions` does is essentially just have IRRd add VRPs to what was fetched as the RPKI JSON blob.

Apologies for bringing this up fairly late, just didn't realise sooner we need support for SLURM here too.

**Comment by mxsasha** [comment]
> The IRRd should periodically refresh the SLURM file (every 10 minutes?), and also reload it at SIGHUP.

The only place where this fits is during the RPKI import / state update process, which would mean it is imported every `roa.import_timer`.

For prefixAssertions: should we do something with the comment? Set the trust anchor string to `SLURM: <comment>` or something?

**Comment by job** [comment]
> > The IRRd should periodically refresh the SLURM file (every 10 minutes?), and also reload it at SIGHUP.
> 
> The only place where this fits is during the RPKI import / state update process, which would mean it is imported every `roa.import_timer`.

good point. That is fine behavior.
 
> For prefixAssertions: should we do something with the comment? Set the trust anchor string to `SLURM: <comment>` or something?

I think just `"ta": "SLURM"` is sufficient. No additional comments needed, if people need those they can read the SLURM file itself.

**Comment by mxsasha** [comment]
> @job - I think this ...
> 
> > In the IRRd configuration we should be able to point at a SLURM file hosted
> 
> ... should be files (plural). It other arenas there's been conversation about the need for more than one SLURM file. I think that irrd should be in the same camp.

What happens if the SLURM files contradict? As in, one has an assertion, for which the other has a filter? ROAs that meet the filter in file 1 are discarded, then a pseudo-ROA is created for the assertion in file 2? Or does the filter in file 1 apply to the assertions in file 2?

**Comment by job** [comment]
> > @job - I think this ...
> > > In the IRRd configuration we should be able to point at a SLURM file hosted
> > 
> > 
> > ... should be files (plural). It other arenas there's been conversation about the need for more than one SLURM file. I think that irrd should be in the same camp.
> 
> What happens if the SLURM files contradict? As in, one has an assertion, for which the other has a filter? ROAs that meet the filter in file 1 are discarded, then a pseudo-ROA is created for the assertion in file 2? Or does the filter in file 1 apply to the assertions in file 2?

For IRRd 4.1.x support for one slurm file is sufficient.
