### ISSUE TITLE
Question: remote status query unsupported or query failed

### ISSUE THREAD

**Issue by mirceaulinic** [irrdnet/irrd#317]
:wave: thanks for this project. We (DigitalOcean) are deploying it right now, and it's very useful so far - great stuff! </offtopic>

I have a bunch of ideas / suggestions that I'll track under separate issues, but for now I would just like to ask a simple question around this infromation in the status page:

```
Remote information:
    NRTM host: whois.ripe.net port 4444
    Remote status query unsupported or query failed
```

I'm noticing the same for `whois.apnic.net port 43`. Both are mirror-first & NRTM-updates type sources. Other sources seem to be fine, e.g.,

```
Remote information:
    NRTM host: rr.ntt.net port 43
    Mirrorable: Yes
    Oldest journal serial number: 1002835
    Newest journal serial number: 1201274
    Last export at serial number: 1201274
```

Is this of any concern at all?

**IRRd version you are running**

4.0.8

**Comment by mxsasha** [comment]
Great to hear it's useful for you!

That message is expected. Not all IRR servers support the `!j` query we use for this. And the protocol isn't very helpful in whether the query is unsupported, rejected, or failed in some way, so IRRd doesn't distinguish that.
