### ISSUE TITLE
Hanging !g query in 4.1

### ISSUE THREAD

**Issue by mxsasha** [irrdnet/irrd#323]
As reported by @ccaputo:

I am seeing a query such as !gas6456 hang apparently indefinitely on IRRd 4.1.0b3 (24cf8812cabe46ea7eaff1c43c9b6a029c30f11c)

**Comment by mxsasha** [comment]
I can reproduce this bug on a Python 3.6 debian install, so it's definitely a confirmed bug.

**Comment by mxsasha** [comment]
@ccaputo When I thought I was reproducing it, it turned out to be a different bug entirely, which I had introduced after the version you are running. So I can't reproduce here.

I take it you meant all `!g` queries hang? If so, there may be an issue with data being preloaded into Redis, or being retrieved.

Which Redis version are you running? `redis-server --version`

Could you run `redis-cli exists irrd-preload-origin-route4` ? It should return 0 or 1. If it is 0, it means preloading data is not reaching redis. On a freshly started IRRd, wait a few minutes before running this command.

I'm expecting this to remain at zero. In that case, can you stop your IRRd, run `redis-cli monitor|cut -d ' ' -f -20` and keep it running, then start IRRd, and share the output? (The `cut` at the end is because this otherwise outputs a ton of data.)

The monitor output should look something like:
```
OK
1592392524.184096 [0 unix:/var/run/redis/redis.sock] "DEL" "irrd-preload-origin-route4" "irrd-preload-origin-route6"
1592392524.365788 [0 unix:/var/run/redis/redis.sock] "SUBSCRIBE" "irrd-preload-reload-channel"
1592392574.752100 [0 unix:/var/run/redis/redis.sock] "MULTI"
1592392574.886452 [0 unix:/var/run/redis/redis.sock] "DEL" "irrd-preload-origin-route4" "irrd-preload-origin-route6"
1592392574.886472 [0 unix:/var/run/redis/redis.sock] "HMSET" "irrd-preload-origin-route4" "BELL_AS577" "207.61.33.32/29,204.101.128.208/29,65.93.255.64/29,67.69.167.16/29,69.157.206.0/25,204.101.207.64/27,[......]
1592392580.155720 [0 unix:/var/run/redis/redis.sock] "HMSET" "irrd-preload-origin-route6" "RADB_AS28573" "2804:14d:7e8f::/48,2804:14c:5bc4::/48,2804:14c:6500::/40,2804:14d:5c91::/48,2804:14c:5fe5::/48,2804:14c:c681::/48,[......]
1592392581.133843 [0 unix:/var/run/redis/redis.sock] "EXEC"
```
More queries may follow after, they're not important for now.

**Comment by ccaputo** [comment]
> I take it you meant all `!g` queries hang? If so, there may be an issue with data being preloaded into Redis, or being retrieved.

I actually didn't check this.  As soon as I hit this issue with one query I reverted to 4.0.8 to get our service back online.

> Which Redis version are you running? `redis-server --version`

It was:

```Redis server v=5.0.8 sha=00000000:0 malloc=jemalloc-5.2.1 bits=64 build=7f9d1c31f73de48f```

> Could you run `redis-cli exists irrd-preload-origin-route4` ? It should return 0 or 1. If it is 0, it means preloading data is not reaching redis. On a freshly started IRRd, wait a few minutes before running this command.

Unfortunately, I am not able to run this because I reverted to 4.0.8.

**Comment by mxsasha** [comment]
Do you happen to know when you tried compared to starting IRRd? When IRRd starts, the preload store needs to be filled for `!g` queries and a few other types. This takes about a minute, and queries made during that time will receive a reply when loading the store is completed. (This does not apply for other updates to the store, except if Redis is restarted while IRRd is running.)

I am thinking just now that the warmup time can be reduced now that 4.1 uses a Redis backend, because we could see how recent the Redis data is and retain it if it's recent enough, eliminating the initial wait when it's just a restart. But that's a later concern.

**Comment by ccaputo** [comment]
> > I take it you meant all `!g` queries hang? If so, there may be an issue with data being preloaded into Redis, or being retrieved.
> 
> I actually didn't check this. As soon as I hit this issue with one query I reverted to 4.0.8 to get our service back online.

I need to correct this.  I dug into the log files and extracted from the start to the finish of an irrd run.  In that I found that several ```!gas``` and ```!6as``` queries were run, timing out, which is what prompted me to dig in further.  While the irrd process started at 08:05:46, the ```!gas``` and ```!6as``` queries were not attempted until 08:12:55.  My final attempt was at 08:22:46.

In case useful, the logfile for the whole process run with ```level: DEBUG```, is attached: [irrd_log.txt](https://github.com/irrdnet/irrd/files/4794029/irrd_log.txt)

**Comment by mxsasha** [comment]
Thanks for the log, this is helpful. It confirms that the preload store starts but never actually finishes loading, causing the queries to hang. No hints on why it fails, so I'll dig into that.

**Comment by mxsasha** [comment]
I can't determine the original cause for this bug based on what we know, but I do see that exceptions are being suppressed incorrectly. So for the next beta I'll add better error logging for this part, and if the issue reoccurs, that should give us more information on the actual original cause.

**Comment by mxsasha** [comment]
@ccaputo Could you try this again with the [4.1.0b4](https://github.com/irrdnet/irrd/releases/tag/v4.1.0b4) release? I don't know what your availability requirements look like, and whether the risk of a short outage is acceptable. If the issue reoccurs, the log should have more information now.

And how did you handle the database migrations when reverting back to 4.0? Did you restore an older copy of the database, or did you do something else?

**Comment by ccaputo** [comment]
> @ccaputo Could you try this again with the [4.1.0b4](https://github.com/irrdnet/irrd/releases/tag/v4.1.0b4) release? I don't know what your availability requirements look like, and whether the risk of a short outage is acceptable. If the issue reoccurs, the log should have more information now.

With v4.1.0b4 on initial startup with a new database table, I did not observe the hangs, but after an irrd restart, I do observe the hangs.

Both on the initial run and after the irrd restart, the following is happening:  (the first and last lines are some 23 megabytes long, so I have trimmed them)
```
2020-06-28 21:22:24,083 irrd[14132]: [irrd.storage.preload#CRITICAL] Updating preload store failed, traceback follows: Command # 2 (HMSET irrd-preload-origin-route4 NTTCOM_AS133948 122.8.0.0/24,119.235.180.0/24,117.46.77.0/24,59.107.128.0/24, [...]  NTTCOM_AS56000 223.255.237.0/24,223.255.239.0/24,223.255.238.0/24 SENTINEL_HASH_CREATED 1) of pipeline caused error: OOM command not allowed when used memory > 'maxmemory'.
Traceback (most recent call last):
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/redis/client.py", line 3911, in _execute_transaction
    response = self.parse_response(connection, '_')
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/redis/client.py", line 3978, in parse_response
    self, connection, command_name, **options)
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/redis/connection.py", line 756, in read_response
    raise response
redis.exceptions.ExecAbortError: Transaction discarded because of previous errors.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/irrd/storage/preload.py", line 298, in run
    self.update(mock_database_handler)
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/irrd/storage/preload.py", line 340, in update
    if self.preloader.update_route_store(new_origin_route4_store, new_origin_route6_store):
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/irrd/storage/preload.py", line 255, in update_route_store
    pipeline.execute()
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/redis/client.py", line 4019, in execute
    return execute(conn, stack, raise_on_error)
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/redis/client.py", line 3914, in _execute_transaction
    raise errors[0][1]
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/redis/client.py", line 3904, in _execute_transaction
    self.parse_response(connection, '_')
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/redis/client.py", line 3978, in parse_response
    self, connection, command_name, **options)
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/redis/connection.py", line 756, in read_response
    raise response
redis.exceptions.ResponseError: Command # 2 (HMSET irrd-preload-origin-route4 NTTCOM_AS133948 122.8.0.0/24,119.235.180.0/24,117.46.77.0/24,59.107.128.0/24,202.83.4.0/22,101.254.89.0/24,123.99.165.0/24,36.0.235.0/24,223.201.78.0/23,1.3.56.0/22, [...]  NTTCOM_AS56000 223.255.237.0/24,223.255.239.0/24,223.255.238.0/24 SENTINEL_HASH_CREATED 1) of pipeline caused error: OOM command not allowed when used memory > 'maxmemory'.
```

A sample of line lengths revealed these are some big data blocks:

```
$ grep SENTINEL_HASH_CREATED irrd.log | awk '{print length}'
23322599
23322512
23323000
23322913
28928938
28928851
28929162
28929075
48752031
48751944
48752048
48751961
48752065
48751978
48752064
48751978
48752064
48751978
```

Redis memory details:

```
# redis-cli info memory
# Memory
used_memory:774328
used_memory_human:756.18K
used_memory_rss:8413184
used_memory_rss_human:8.02M
used_memory_peak:89619992
used_memory_peak_human:85.47M
used_memory_peak_perc:0.86%
used_memory_overhead:702758
used_memory_startup:517688
used_memory_dataset:71570
used_memory_dataset_perc:27.89%
allocator_allocated:712392
allocator_active:8375296
allocator_resident:8375296
total_system_memory:135168192512
total_system_memory_human:125.89G
used_memory_lua:37888
used_memory_lua_human:37.00K
used_memory_scripts:0
used_memory_scripts_human:0B
number_of_cached_scripts:0
maxmemory:67108864
maxmemory_human:64.00M
maxmemory_policy:noeviction
allocator_frag_ratio:11.76
allocator_frag_bytes:7662904
allocator_rss_ratio:1.00
allocator_rss_bytes:0
rss_overhead_ratio:1.00
rss_overhead_bytes:37888
mem_fragmentation_ratio:11.81
mem_fragmentation_bytes:7700792
mem_not_counted_for_evict:0
mem_replication_backlog:0
mem_clients_slaves:0
mem_clients_normal:185070
mem_aof_buffer:0
mem_allocator:jemalloc-5.2.1
active_defrag_running:0
lazyfree_pending_objects:0
```

I have the redis config "save" lines commented out per guidance from https://irrd.readthedocs.io/en/latest/admins/deployment.html#deployment-redis-configuration .  Based on the above OOM hint, I changed my redis config's default ```maxmemory``` setting from 64M to 1GB.  I then stopped irrd, restarted redis, started irrd and all appears to work well now.

```
# redis-cli info memory
# Memory
used_memory:75281608
used_memory_human:71.79M
used_memory_rss:157470720
used_memory_rss_human:150.18M
used_memory_peak:75350784
used_memory_peak_human:71.86M
used_memory_peak_perc:99.91%
used_memory_overhead:602362
used_memory_startup:518712
used_memory_dataset:74679246
used_memory_dataset_perc:99.89%
allocator_allocated:75219688
allocator_active:157432832
allocator_resident:157432832
total_system_memory:135168192512
total_system_memory_human:125.89G
used_memory_lua:37888
used_memory_lua_human:37.00K
used_memory_scripts:0
used_memory_scripts_human:0B
number_of_cached_scripts:0
maxmemory:1073741824
maxmemory_human:1.00G
maxmemory_policy:noeviction
allocator_frag_ratio:2.09
allocator_frag_bytes:82213144
allocator_rss_ratio:1.00
allocator_rss_bytes:0
rss_overhead_ratio:1.00
rss_overhead_bytes:37888
mem_fragmentation_ratio:2.09
mem_fragmentation_bytes:82251032
mem_not_counted_for_evict:0
mem_replication_backlog:0
mem_clients_slaves:0
mem_clients_normal:83538
mem_aof_buffer:0
mem_allocator:jemalloc-5.2.1
active_defrag_running:0
lazyfree_pending_objects:0
```

I recommend the redis documentation and release notes be updated to include a recommended ```maxmemory``` setting for the redis config and/or a config check upon startup to confirm adequate redis maxmemory setting.

NOTE: I have tested the quality of the results, with respect to the many thousands of queries we perform to inform our route servers.  While the data with 4.1.0b4 is good as compared to 4.0.8, I am finding 4.1.0b4 to be considerable slower.  As an example, we perform about 12k ```!gas##``` and 9.6k ```!6as###``` queries every hour.  With 4.0.8 this process takes under 4 minutes, but with 4.1.0b4 it is taking over 14 minutes.  Any idea why the slowdown?

> And how did you handle the database migrations when reverting back to 4.0? Did you restore an older copy of the database, or did you do something else?

When downgrading I drop the irrd postgres table and reinitialize it.

**Comment by mxsasha** [comment]
Thanks, great find! I think I haven't run into it myself because different Redis packages may have different defaults. And it makes sense that 64MB is too small. I'll add this to the docs.
