### ISSUE TITLE
documentation does not match installation

### ISSUE THREAD

**Issue by icing** [irrdnet/irrd#334]
I followed the `deployment` instructions to make a test installation of irrd in a docker image with a debian-stable. I basically do:

```
...
RUN apt-get install -y python3 python3-pip virtualenv
RUN groupadd -r irrd && useradd --no-log-init -r -g irrd -d /home/irrd -m irrd
RUN mkdir -p /var/log/irrd && chown irrd.irrd /var/log/irrd
COPY irrd/irrd.yaml /etc/irrd.yaml
COPY bin/irrd /dtag/bin/irrd
USER irrd
RUN virtualenv -p python3 /home/irrd/irrd-venv
RUN /home/irrd/irrd-venv/bin/pip3 install irrd==4.0.8
...
```

When I startup postgresql and run `su - irrd -c /home/irrd/irrd-venv/bin/irrd_database_upgrade` it reports that the database is fine and there is nothing to ugprade.

Then I want to start `/home/irrd/irrd-venv/bin/irrd`, but the file does not exist.

Looking into the venv site-packages, I see:

```
> ls -l /home/irrd/irrd-venv/lib/python3.7/site-packages/irrd
-rw-r--r-- 1 irrd irrd   22 Jun 25 12:19 __init__.py
drwxr-xr-x 2 irrd irrd 4096 Jun 25 12:19 __pycache__
drwxr-xr-x 3 irrd irrd 4096 Jun 25 12:19 conf
drwxr-xr-x 3 irrd irrd 4096 Jun 25 12:19 mirroring
drwxr-xr-x 3 irrd irrd 4096 Jun 25 12:19 rpsl
drwxr-xr-x 3 irrd irrd 4096 Jun 25 12:19 scripts
drwxr-xr-x 5 irrd irrd 4096 Jun 25 12:19 server
drwxr-xr-x 4 irrd irrd 4096 Jun 25 12:19 storage
drwxr-xr-x 3 irrd irrd 4096 Jun 25 12:19 updates
drwxr-xr-x 3 irrd irrd 4096 Jun 25 12:19 utils
```

Shouldn't there be a `daemon` as well?

Thanks for the help!

**Comment by mxsasha** [comment]
Those are only present in IRRd 4.1 (currently in beta). You may have read the documentation for that instead of [4.0.8](https://irrd.readthedocs.io/en/v4.0.8/admins/deployment.html), which is what you are installing :)

**Comment by icing** [comment]
Thanks for the quick reply!
