### ISSUE TITLE
!J - monitoring

### ISSUE THREAD

**Issue by job** [irrdnet/irrd#339]
related to https://github.com/irrdnet/irrd/issues/322

Can a new `!J` command be developed (which outputs JSON rather than WHOIS `:` separated output)

The goal of this command is to offer insight into: where was `.CURRENTSERIAL` located and which dumps were loaded, what was the serial at the time of fetching, what is the current local serial, what is the current remote serial.

perhaps some timestamps can be added as well, and the order of the databases should be clear from the JSON blob too

**Comment by job** [comment]
@ccaputo your input welcome too!

**Comment by ccaputo** [comment]
> @ccaputo your input welcome too!

Sounds good to me.  I also like what you indicated in #322 about maintaining existing ```!j``` functionality for backward compatibility.  The http status method is too slow & bulky (in terms of quantity of output) for quickly checking to see if my instance is sync'ed up with servers it is mirroring.

**Comment by mahtin** [comment]
It’s called `RDAP`. If you want JSON then implement an RDAP endpoint - or put a different way - please deprecate vs. enhance port-43.

**Comment by job** [comment]
@mahtin you are missing the point entirely

**Comment by job** [comment]
> > @ccaputo your input welcome too!
> 
> Sounds good to me. I also like what you indicated in #322 about maintaining existing `!j` functionality for backward compatibility. The http status method is too slow & bulky (in terms of quantity of output) for quickly checking to see if my instance is sync'ed up with servers it is mirroring.

yes, `!j` should continue to exist with backwardscompatbility in mind, which i guess means that it shows the latest serial it received from the *remote* NRTM peer

**Comment by mahtin** [comment]
@job - I saw `JSON`. I saw `whois`. I had a visceral reaction. Sorry.

**Comment by ccaputo** [comment]
> @job - I saw `JSON`. I saw `whois`. I had a visceral reaction. Sorry.

Man's got a point.

**Comment by mxsasha** [comment]
Here's what this looks like now:
```
{
 "TEST1": {
  "authoritative": true,
  "object_class_filter": [
   "route"
  ],
  "rpki_enabled": true,
  "local_journal_kept": false,
  "serial_oldest_journal": 10,
  "serial_newest_journal": 10,
  "serial_last_export": 10,
  "serial_newest_mirror": 500,
  "last_update": "2020-01-01T00:00:00+00:00"
 },
 "TEST2": {
  "authoritative": false,
  "object_class_filter": null,
  "rpki_enabled": false,
  "local_journal_kept": true,
  "serial_oldest_journal": null,
  "serial_newest_journal": null,
  "serial_last_export": null,
  "serial_newest_mirror": 20,
  "last_update": "2020-01-01T00:00:00+00:00"
 }
}
```
Details about each field are [in the docs](https://irrd.readthedocs.io/en/latest/users/queries.html).

**Comment by job** [comment]
small nit: `rpki_enabled` -> `"rpki_rov_filter":` (`true | false`)
