### ISSUE TITLE
Non-UTF-8 character escapes are problematic, how about we don't do that anymore?

### ISSUE THREAD

**Issue by morrowc** [irrdnet/irrd#358]
**Describe the bug**
When parsing irr output for objects it's expected (based on RFC2622) that only ASCII characters be permitted in attributes or values. There are cases today which do not conform to this standard.

**To Reproduce**
query for:  187.73.32.0/22 (from RADB for instance)

**Expected behaviour**
See only ASCII characters, not UTF-8 nor invalid UTF-8 escape sequences
get this instead:
  descr:          Digirati Inform\xe1tica, Servi\xe7os e Telecomunica\xe7\xf5es

**IRRd version you are running**
4.0.0

**Additional context**
Originally reported by Dan van Allen... I'm just carrier pidgeoning it to the githubs.
(I'm working on a repro test in the codebase, so don't action this until I update.. unless of course you know:"Derp, of course it's Foo in the Bar package, fixed!" in 2 seconds or less)

**Comment by job** [comment]
Maybe the `vis` algorithm should be used to flatten input from NRTM mirrors?

The RADB original:
```
descr:      Digirati Informática, Serviços e Telecomunicações
```

The current version at NTT:
```
descr:          Digirati Inform\xe1tica, Servi\xe7os e Telecomunica\xe7\xf5es
```

Perhaps an option to handle it as well?

```
job@vurt ~$ whois -hwhois.radb.net 187.73.32.0/22 | grep descr | vis      
descr:      Digirati Inform\M-atica, Servi\M-gos e Telecomunica\M-g\M-ues
```

see https://man.openbsd.org/vis

**Comment by mxsasha** [comment]
This is kind of a known issue. Different databases use different undocumented encodings, which they may or may not do correctly or consistently. Technically the RFC says ascii, but I think ascii-only databases are the minority in the current IRR ecosystem.

@job I see that using vis makes the output different, but is this really better?

**Comment by mahtin** [comment]
Issue #88 says "We should consider RDAP support in phase 2". Solving this issue on whois port 43 is a futile process. Let's concentrate on enjoying the wonders of a [rfc7482](https://tools.ietf.org/html/rfc7482) friendly life!

**Comment by mxsasha** [comment]
I don't think there's more on this that we can do for now. IRRd is UTF-8 on whois and HTTP interface. NRTMv4 should also define a specific character set, or at least a specification of the character set.
