### ISSUE TITLE
Prevent expansion of 'unreasonably' large members of an as-set

### ISSUE THREAD

**Issue by job** [irrdnet/irrd#36]
I'd like to automatically prevent expansion of the top 100 largest AS-SETs when they are included in other AS-SETs.

In other words, if anyone includes `AS2914:AS-GLOBAL` in their AS-SET - we should have a capability to ignore that `AS2914:AS-GLOBAL` is a member of that AS-SET.

**Comment by mahtin** [comment]
There’s two controls that would be similar to this. 

1) Limiting the final size of a computed filter list
2) Limiting the size of an included as-set

You’ve defined the second option; however the first option is just as valid. Implementing both may make for some specific choices. For example, by limiting AS2914:AS-GLOBAL, maybe you want to still include just the core ASN (2914), or maybe just first or second level ASNs, or something else. (I see Lua in irrd4’s future!)

**Comment by troy2914** [comment]
Speaking from experience, AS2914 is more likely to be included in an as-set then AS2914:AS-GLOBAL.

Also we only want to expand AS2914 when it's in in a AS2914:AS-* as-set.  Think there's another ticket for phase 2 for that.

**Comment by mxsasha** [comment]
This is now part of #422
