### ISSUE TITLE
Unable to run export - internal database status is empty

### ISSUE THREAD

**Issue by laxxie** [irrdnet/irrd#375]
Hi Guys,

we want to set up our own IRRD instance and so we are testing with the latest stable version and an Ubuntu 20.04.
The import of the RIPE and ARIN dataset is working like a charm but we have a problem with the export.

> 2020-08-18 15:28:39,104 irrd[159562]: [irrd.mirroring.mirror_runners_export#INFO] Starting a source export for AUTHDATABASE to /home/irrd/export
> 2020-08-18 15:28:39,110 irrd[159562]: [irrd.mirroring.mirror_runners_export#ERROR] Unable to run export for AUTHDATABASE, internal database status is empty.

The IRRD is running as the user irrd and /home/irrd and all subfolders belong to this user. 
I don't get it what we have to do to get the export working. Does anybody have an advice?

Thanks

**Comment by mxsasha** [comment]
What's happening is that your config has an authoritative database, called AUTHDATABASE, perhaps taken from the example config? Apparently it's configured to run exports, but as I'm guessing no objects were added (or no journal is kept), the serial number of the database is unknown. IRRd can't export a CURRENTSERIAL for AUTHDATABASE, therefore the AUTHDATABASE export fails.

In 4.1 IRRd will just skip the CURRENTSERIAL file in this case (#356). But, if you're not actually using AUTHDATABASE, you could just remove it from your config.

This error does not affect any other IRRd processes, or exports for other sources.

**Comment by laxxie** [comment]
Ok, perhaps i just misinterpreted what is the purpose of the AUTHDATABASE.
Am i right if i need the AUTHDATABASE just for objects which i created locally? So neither the RIPE or ARIN dataset were exported to AUTHDATABASE? 
So summarizing the import of the RIPE and ARIN is enough to get the results from the IRRD instance and we don't need an export

**Comment by mxsasha** [comment]
Yes, exactly. All the sources you configure basically function independently. So in theory, you could configure a local export for RIPE, and your IRRd instance would produce export files for your view of RIPE. But for querying, you don't need to run any exports.
Authoritative databases are used when your instance is supposed to be the authoritative source, and accept incoming emails for changes from users. For example the IRRd instance on rr.ntt.net is set to be authoritative for NTTCOM, but my own test setups are not - they use mirroring.
