### ISSUE TITLE
Re-introduce support for synchronised mirror serials

### ISSUE THREAD

**Issue by mxsasha** [irrdnet/irrd#382]
ARIN's setup depends on the 4.0 behaviour of synchronising NRTM serials with the NRTM source. It should be possible to add support for this, as long as it isn't combined with RPKI or scope filtering.

**Comment by job** [comment]
the expectation is that ARIN (specifically for `ARIN-NONAUTH`) can use the RPKI filtering feature. It would be good to consider how to engineer the pipeline to get RPKI origin validation going in this environment too

**Comment by job** [comment]
@mxsasha are serials not synced if rpki + scope is disabled? exhibiting 4.0 behavior if those two things are either disabled in the config (or not present in the case of scope) could be a reasonable default, right?

**Comment by mxsasha** [comment]
> @mxsasha are serials not synced if rpki + scope is disabled? exhibiting 4.0 behavior if those two things are either disabled in the config (or not present in the case of scope) could be a reasonable default, right?

There is an additional catch: if RPKI or scopefilter was enabled at any point, you need to do a full database reload from the mirror, before synchronised serials can be used. All mirroring clients will also have to do a reload. Because with either enabled, serials run out of sync rapidly, and that is not recoverable without everyone starting from a fresh reload and a fresh journal.

So an option could be: synchronised serials by default. If at any time RPKI or scopefilter are enabled for that source, disable synchronised serials until a full reload happens (while RPKI and scopefilter are disabled). `!J` could state whether synchronised serials are currently enabled for the source.
