### ISSUE TITLE
Force new AS-SETs to be structured hierarchically

### ISSUE THREAD

**Issue by job** [irrdnet/irrd#408]
There are two naming variants possible when creating `AS-SET` objects: flat (example: `AS-SNIJDERS`) or hierarchical (example: `AS15562:AS-SNIJDERS`).

A next version of IRRd would probably benefit from encouraging users to create `AS-SET` objects following the hierarchical convention, this can be achieved by rejecting *new* `AS-SET` objects that do not follow the hierarchical convention.

The submitter of the object should be presented with a clear error and a suggestion what to do instead of a flat name.

Thoughts?

**Comment by job** [comment]
Benefits of hierarchical naming: helps avoid naming collisions, and also helps identify which BGP network the `AS-SET` object relates to

**Comment by mxsasha** [comment]
Seems reasonable. So the effective requirement would be: each newly created as-set in an authoritative database, should start with "ASxxxx:"?

**Comment by job** [comment]
Yes
