### ISSUE TITLE
Investigate database locking by RPKI importer

### ISSUE THREAD

**Issue by mxsasha** [irrdnet/irrd#446]
The RPKI importer may be locking the database for a while, requiring other changes to wait. This shouldn't happen, because it should not be making explicit locks and does not affect the same rows as any other operation. It's also possible something entirely different is happening. Needs investigation.

**Comment by job** [comment]
does this affect 4.1?

**Comment by mxsasha** [comment]
Yes. Between the "Running full ROA import from" and "ROA import from ... imported ..." lines, all other changes are suspended, but resumed later. The window is about 6 minutes on my mac.

We can make a 4.1.1 release with this fix?

**Comment by job** [comment]
A 4.1.1 would be good indeed

**Comment by mxsasha** [comment]
4.1.1 released
