### ISSUE TITLE
How to delete source data from PostgreSQL database

### ISSUE THREAD

**Issue by ma-anazawa** [irrdnet/irrd#458]
Hi,

When I delete LEVEL3 from sources in the irrd.yaml file, LEVEL3 is not deleted from the PostgreSQL database.
Please tell me how to delete LEVEL3 on the PostgreSQL database as well.

IRRD version 4.1.0

Thanks for your great work!

**Comment by mxsasha** [comment]
This is intentional, because we wouldn't want a misconfiguration to lead to unrecoverable data loss. I'm not sure whether this is common enough to introduce a command for, but you can delete it manually with a few PostgreSQL queries:
```
irrd=# DELETE FROM rpsl_database_journal WHERE source='LEVEL3';
irrd=# DELETE FROM rpsl_objects WHERE source='LEVEL3';
irrd=# DELETE FROM database_status WHERE source='LEVEL3';
