### ISSUE TITLE
rpsl parser usage questions

### ISSUE THREAD

**Issue by talent-nansy** [irrdnet/irrd#485]
I'm having a problem using rpsl parser. 
I created a new python file and import '_test_rpsl_objects_' . 

```
import datetime

import pytest
from IPy import IP
from pytest import raises
from pytz import timezone

import sys
from os.path import dirname
import os
path = dirname(dirname(dirname(os.getcwd())))
print(path)
sys.path.append(path)

from test_rpsl_objects import TestRPSLParsingGeneric
ts = TestRPSLParsingGeneric()
ts.test_malformed_empty_line()
```

However, I keep get Error Information that 'ImportError: attempted relative import with no known parent package' .
![image](https://user-images.githubusercontent.com/16119436/114123322-a91c2b00-9924-11eb-82f0-f3dafec7fdae.png)

I would appreciate that you can show me a way to use these parsers.
Best wishes.

**Comment by mxsasha** [comment]
It seems like you're trying to use the parser tests, rathre than the actual parser itself. Here's an example of parsing a sample object from a Python script outside irrd:

```
>>> from irrd.rpsl.rpsl_objects import rpsl_object_from_text
>>> obj = rpsl_object_from_text("route: 192.0.2.0/24\norigin: AS65537\nsource: DEMO")
>>> obj.pk()
'192.0.2.0/24AS65537'
>>> obj.prefix
IP('192.0.2.0/24')
>>> obj.messages
<irrd.rpsl.parser_state.RPSLParserMessages object at 0x10b3e5450>
>>> obj.messages.messages()
['Mandatory attribute "mnt-by" on object route is missing']
```

I should add that the RPSL parser in IRRd was designed to be decoupled from other parts, so it should be possible to use the parser independently. But this is not an actively supported or documented use of irrd, and API stability between versions is not guaranteed.

**Comment by talent-nansy** [comment]
Thanks a lot for your help. It worked for me. :)
I will pay attention to the API changes between different versions, thanks again.

**Comment by fischerdouglas** [comment]
> I should add that the RPSL parser in IRRd was designed to be decoupled from other parts, so it should be possible to use the parser independently.

I seem a good tool to be used in conjunction with Netbox, to generate and parse before-send, IRR Objects based on Netbox database to the IRR database of choice.
