### ISSUE TITLE
Clarify documentation on CPython vs PyPy

### ISSUE THREAD

**Issue by mxsasha** [irrdnet/irrd#488]
The deployment docs and 4.2 release notes should be clearer on choosing between CPython and PyPy. While PyPy has some performance benefits, it can also be much harder to deploy in some setups. The current documentation can be improved a bit in helping users make that choice.

**Comment by rubenskuhl** [comment]
Moving to CPython indeed made some packages that refused to build, to start building. But even so, irrd 4.2.0b1 doesn't build until wheel is added to the virtual environment. 
Sequence that worked:
 python3 -m venv /home/irrd/irrd-venv
/home/irrd/irrd-venv/bin/pip3 install wheel
/home/irrd/irrd-venv/bin/pip3 install /home/irrd/irrd-4.2.0b1 (where the path is the location of the download)

**Comment by mxsasha** [comment]
> Moving to CPython indeed made some packages that refused to build, to start building. But even so, irrd 4.2.0b1 doesn't build until wheel is added to the virtual environment.

This sounds like a separate problem, or problems, but still a bug. I can reproduce the error `error: invalid command 'bdist_wheel'` during pip install on the tgz, although the package still seems to install after that. I will add wheel to the dependencies to fix this.

I am confused on whether you have any other issues on either CPython or PyPy. If you do, could you tell me:
- What were the errors from the install?
- What is your python version? `python3 -V`
- What is your pip version? `pip3 -V`
- Did you install the tgz or the whl file?

**Comment by rubenskuhl** [comment]
Errors:
``/home/irrd/irrd-venv/bin/pip3 install /home/irrd/irrd-4.2.0b1
(everything that worked omitted here)
Building wheels for collected packages: irrd, IPy, ordered-set
Building wheel for irrd (setup.py) ... error
ERROR: Command errored out with exit status 1:
command: /home/irrd/irrd-venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-w8uu16y7/setup.py'"'"'; file='"'"'/tmp/pip-req-build-w8uu16y7/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(file);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, file, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-j4ktvfte
cwd: /tmp/pip-req-build-w8uu16y7/
Complete output (6 lines):
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
or: setup.py --help [cmd1 cmd2 ...]
or: setup.py --help-commands
or: setup.py cmd --help

error: invalid command 'bdist_wheel'
ERROR: Failed building wheel for irrd
Running setup.py clean for irrd
Building wheel for IPy (setup.py) ... error
ERROR: Command errored out with exit status 1:
command: /home/irrd/irrd-venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-jb48oq_3/IPy/setup.py'"'"'; file='"'"'/tmp/pip-install-jb48oq_3/IPy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(file);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, file, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-jvlz76b9
cwd: /tmp/pip-install-jb48oq_3/IPy/
Complete output (8 lines):
/home/irrd/irrd-venv/lib/python3.8/site-packages/setuptools/dist.py:473: UserWarning: Normalizing '1.01' to '1.1'
warnings.warn(
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
or: setup.py --help [cmd1 cmd2 ...]
or: setup.py --help-commands
or: setup.py cmd --help

error: invalid command 'bdist_wheel'
ERROR: Failed building wheel for IPy
Running setup.py clean for IPy
Building wheel for ordered-set (setup.py) ... error
ERROR: Command errored out with exit status 1:
command: /home/irrd/irrd-venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-jb48oq_3/ordered-set/setup.py'"'"'; file='"'"'/tmp/pip-install-jb48oq_3/ordered-set/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(file);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, file, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-814pkluy
cwd: /tmp/pip-install-jb48oq_3/ordered-set/
Complete output (6 lines):
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
or: setup.py --help [cmd1 cmd2 ...]
or: setup.py --help-commands
or: setup.py cmd --help

error: invalid command 'bdist_wheel'
ERROR: Failed building wheel for ordered-set``

Python version: python3 -V
Python 3.8.5

pip version: pip3 -V   
pip 20.0.2 from /usr/lib/python3/dist-packages/pip (python 3.8)

We installed the tgz file.

**Comment by rubenskuhl** [comment]
The issues above were with CPython. PyPy failed sooner on PyYAML and I was unable to work around it.

**Comment by mxsasha** [comment]
> The issues above were with CPython. PyPy failed sooner on PyYAML and I was unable to work around it.

I will fix the CPython issue, but without more details I can't reproduce your PyPy install issue.

**Comment by rubenskuhl** [comment]
> > The issues above were with CPython. PyPy failed sooner on PyYAML and I was unable to work around it.
> 
> I will fix the CPython issue, but without more details I can't reproduce your PyPy install issue.

Collecting IPy==1.01
  Using cached IPy-1.01.tar.gz (33 kB)
Collecting PyYAML==5.4.1
  Using cached PyYAML-5.4.1.tar.gz (175 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /home/irrd/irrd-test-venv/bin/pypy3-c /home/irrd/irrd-test-venv/share/python-wheels/pep517-0.8.2-py2.py3-none-any.whl/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpp8yqys9a
       cwd: /tmp/pip-install-_ae0jsgu/PyYAML
  Complete output (1 lines):
  /home/irrd/irrd-test-venv/bin/pypy3-c: can't find '__main__' module in '/home/irrd/irrd-test-venv/share/python-wheels/pep517-0.8.2-py2.py3-none-any.whl/pep517/_in_process.py'
  ----------------------------------------
ERROR: Command errored out with exit status 1: /home/irrd/irrd-test-venv/bin/pypy3-c /home/irrd/irrd-test-venv/share/python-wheels/pep517-0.8.2-py2.py3-none-any.whl/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpp8yqys9a Check the logs for full command output.

**Comment by mxsasha** [comment]
> ERROR: Command errored out with exit status 1: /home/irrd/irrd-test-venv/bin/pypy3-c /home/irrd/irrd-test-venv/share/python-wheels/pep517-0.8.2-py2.py3-none-any.whl/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpp8yqys9a Check the logs for full command output.

This is a challenging one - [this pip issue](https://github.com/pypa/pip/issues/7946) suggests it may be an issue with your local pip install, and using `--reinstall` with your pip install may help.
