### ISSUE TITLE
systemd erases /var/run and doesn't recreate it

### ISSUE THREAD

**Issue by rubenskuhl** [irrdnet/irrd#489]
**Describe the bug**
irrd requires a /var/run (or /run) directory to store PID. It's erased each time by systemd. 

**To Reproduce**
Reboot

**Expected behaviour**
Automatic recreation

**IRRd version you are running**
E.g. 4.2.0b1

**Additional context**
It can be solved by adding, in the Service section,
RuntimeDirectory=irrd 
in the systemd configuration instructions (https://irrd.readthedocs.io/en/latest/admins/deployment/#systemd-configuration)

**Comment by mxsasha** [comment]
The current example of systemd suggests putting the pidfile in `/home/irrd/` though, which already exists if someone follows the examples from the deployment guide?

**Comment by mxsasha** [comment]
@rubenskuhl any thoughts on this? I'm happy to update the sample in the docs, but was puzzled by what I commented before.
