### ISSUE TITLE
Can't disable inetnum

### ISSUE THREAD

**Issue by rubenskuhl** [irrdnet/irrd#496]
**Describe the bug**
All attempts to turn compatibility.inetnum_search_disabled on failed. 

**To Reproduce**
Try adding the option to the config file. The example doesn't include this section, being suggestive that it might not be supported.

**Expected behaviour**
Either it should work or be removed from documentation if it's no longer in the code.
It's possible to be a config error, so an example in the docs would be welcome. 

**IRRd version you are running**
4.2.0b1

**Additional context**

**Comment by mxsasha** [comment]
> All attempts to turn compatibility.inetnum_search_disabled on failed.

How exactly did it fail? Note that it does not enforce that no inetnums are ever processed - it means you promise IRRd you're not doing that, or if you do, you're willing to accept incomplete query responses. Basically, it [enables an optimised query method](https://irrd.readthedocs.io/en/latest/users/queries/#performance-of-prefix-queries) that is much faster but can't work for inetnums.

It might be better if we did enforce that IRRd will reject inetnums too - or more generally: that IRRd can block creation of certain object types. This is supported for mirroring now, but not for authoritative. The inetnum_search_disabled option would then be obsolete.

But, the current implementation is limited to enabling a more efficient prefix query method.

**Comment by rubenskuhl** [comment]
It failed as in saying the config was wrong and refusing to start the service.

**Comment by mxsasha** [comment]
This works for me, but looking at the docs I realise that they might be ambiguous: when the docs say `compatibility.inetnum_search_disabled`, it means a config like:

```
irrd:
    compatibility:
        inetnum_search_disabled: true
```

**Comment by rubenskuhl** [comment]
> This works for me, but looking at the docs I realise that they might be ambiguous: when the docs say `compatibility.inetnum_search_disabled`, it means a config like:
> 
> ```
> irrd:
>     compatibility:
>         inetnum_search_disabled: true
> ```

Defining as this it worked.
