### ISSUE TITLE
Add support new rpki-client JSON format?

### ISSUE THREAD

**Issue by job** [irrdnet/irrd#499]
The `rpki-client` JSON output format is slightly changing, an example of the new format can be found here: http://console.rpki-client.org/vrps.json

1) the `asn` value no longer is a string prefixed with `AS`, but rather just a simple integer.

~~2) a new `expires` key has been added: the value signifies when the VRP will expire in of seconds since the Epoch, UTC, given the expiration timers on current chain of CRLs & CAs applicable to a given VRP. Generally objects will be between 32 and 72 hours from their expiration, and every time `rpki-client` refreshes its data the expiration time is bumped forwards. Perhaps this can be used for more easy garbage collection / RPKI updating? (or just ignored if it isn't useful in irrd)~~

**Comment by mxsasha** [comment]
For point 1, this is already mostly supported, the only issue is that SLURM validationOutputFilters would not be correctly matched.

For point 2, maybe, we can take this into consideration in #497. Otherwise, extra data in the JSON is ignored, so it won't break anything.

**Comment by job** [comment]
Dear @mxsasha ,

It appears _point 1_ has become a blocker for some ISPs to upgrade their RPKI validators.

Would it be possible to resolve _point 1_ with a backport to 4.1.x ?

Kind regards,

Job

**Comment by job** [comment]
Now both variants are supported?

**Comment by mxsasha** [comment]
It should, yes. But will do a bit more testing.

**Comment by job** [comment]
I realize I should've made two issues, I updated the original posting :-)

**Comment by job** [comment]
I tested this PR applied to b16bd506e494f2c6dc81a3e65a3c353ca4525e6d

both formats (old and new) work correctly
