### ISSUE TITLE
Ability to submit objects via a HTTPS based API

### ISSUE THREAD

**Issue by job** [irrdnet/irrd#5]

**Comment by Gunni** [comment]
I wonder if it is possible to submit gpg signed objects using this method, so i can have mntner without a password (just sso or key-cert).

**Comment by job** [comment]
Authentication depends on #122. We won't support `CRYPT-PW` or `MD5-PW` or `PGP` for the HTTPS API.

* API must be able to accept structured input (probably XML formatted) and good ole' plaintext RPSL 
* Add/update/remove objects via HTTPS API
* All port 43 queries (such as `!i`) must have an equivalent in the HTTPS API
* HTTP query pipelining or multiplexing must be available to make things fast enough

**Comment by job** [comment]
Overall goal is to be able to interact with IRRd without having to use any email transport

**Comment by kkirsche** [comment]
Is there an existing HTTP API which this would be an extension of, or would this be a brand new API implementation into the irrd4 application?

**Comment by job** [comment]
@kkirsche Thank you for your interest in developing code for this aspect. Please hold off on working on this until there is some clarify on what NTT will do or not do in this context.

**Comment by mxsasha** [comment]
This was added in d1189cbd767d815af3007ee7358b29542c0a06da: https://irrd.readthedocs.io/en/latest/users/database-changes/
