### ISSUE TITLE
RPKI importer may not time out HTTP connection properly

### ISSUE THREAD

**Issue by rubenskuhl** [irrdnet/irrd#510]
**Describe the bug**
RPKI not updating at configured frequency

Current time: Thu 10 Jun 2021 07:36:42 PM UTC
From /status: 
Status for RPKI
-------------------
Local information:
    Authoritative: No
    Object class filter: None
    Oldest serial seen: None
    Newest serial seen: None
    Oldest local journal serial number: None
    Newest local journal serial number: None
    Last export at serial number: None
    Newest serial number mirrored: None
    Synchronised NRTM serials: No
    Last update: 2021-06-07 00:02:48.469714+00:00
    Local journal kept: No
    Last import error occurred at: None
    RPKI validation enabled: Yes
    Scope filter enabled: Yes

Remote information:
    No NRTM host configured.

-------------------

From config file:
rpki:

        roa_source: https://rpki.gin.ntt.net/api/export.json

        roa_import_timer: 3600

        pseudo_irr_remarks: |

            This AS{asn} route object represents routing data retrieved

            from the RPKI. This route object is the result of an automated

            RPKI-to-IRR conversion process performed by IRRd.

        notify_invalid_enabled: true

Memory availability doesn't seem an issue:

 free -g
              total        used        free      shared  buff/cache   available
Mem:             31          12           7           6          10          11
Swap:             3           0           3

**To Reproduce**
/status

**Expected behaviour**
The timer on the config file should be followed to trigger RPKI source updates

**IRRd version you are running**
E.g. 4.2.0b1

**Additional context**

**Comment by mxsasha** [comment]
I think this might be the `last update` time not updating, rather than the RPKI importer not running. Are you seeing any log messages about RPKI importer runs?

**Comment by rubenskuhl** [comment]
No, the only references to RPKI in logs is from NTRM of other sources. And we got to this exactly because an invalid entry wasn't being removed after a ROA has been published.

**Comment by mxsasha** [comment]
Is there any irrd process running that has RPKI in the name? And I imagine the last import from 2021-06-07 00:02:48.469714+00:00 must have left something in the logs?

**Comment by rubenskuhl** [comment]
> Is there any irrd process running that has RPKI in the name? 

```
irrd@bgp:~$ ps aux | grep RPKI
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
irrd       11909  0.0  0.1 129780 41000 ?        S    Jun07   0:00 irrd-ROAImportRunner-RPKI
```

And I imagine the last import from 2021-06-07 00:02:48.469714+00:00 must have left something in the logs?

021-06-07 00:06:06,117 irrd[10424]: [irrd.mirroring.mirror_runners_import#INFO] RPKI status updated for all routes, 0 newly valid, 0 newly invalid, 0 newly not_found routes, 0 emails sent to contacts of newly invalid authoritative objects
2021-06-07 00:56:44,327 irrd[2164]: [irrd.mirroring.scheduler#DEBUG] Started new process ROAImportRunner-RPKI for mirror import/export for RPKI

In the same day we had some RPKI-guided rejections:

ERROR: RPKI ROAs were found that conflict with this object. (This IRRd refreshes ROAs every 3600 seconds.)
ERROR: RPKI ROAs were found that conflict with this object. (This IRRd refreshes ROAs every 3600 seconds.)
ERROR: RPKI ROAs were found that conflict with this object. (This IRRd refreshes ROAs every 3600 seconds.)
ERROR: RPKI ROAs were found that conflict with this object. (This IRRd refreshes ROAs every 3600 seconds.)
ERROR: RPKI ROAs were found that conflict with this object. (This IRRd refreshes ROAs every 3600 seconds.)
ERROR: RPKI ROAs were found that conflict with this object. (This IRRd refreshes ROAs every 3600 seconds.)

But no message saying something like it has died, crashed or something like that. 

The following days no other messages for RPKI appear in the logs.

**Comment by mxsasha** [comment]
So, it seems 11909 got stuck somehow. The scheduler detects that as the RPKI importer still running, and therefore will not start another one. If I read that ps right, the CPU time is zero seconds, which means it must have failed very early on. RPKI importing is a CPU intense process. Early failure also makes sense with 41MB memory use.

Could you run strace against the process to see if it is hanging on any IO thing?

To get your RPKI moving again, you can kill 11909, with SIGKILL if needed. Another RPKI import should then start within 30 seconds or so. But then we lose the ability to dig into the process, so please try to strace it first.

**Comment by rubenskuhl** [comment]
> So, it seems 11909 got stuck somehow. The scheduler detects that as the RPKI importer still running, and therefore will not start another one. If I read that ps right, the CPU time is zero seconds, which means it must have failed very early on. RPKI importing is a CPU intense process. Early failure also makes sense with 41MB memory use.
> 
> Could you run strace against the process to see if it is hanging on any IO thing?

sudo strace -p 11909
strace: Process 11909 attached
read(16, 

(and keeps at that)


> To get your RPKI moving again, you can kill 11909, with SIGKILL if needed. Another RPKI import should then start within 30 seconds or so. But then we lose the ability to dig into the process, so please try to strace it first.

I will refrain on it until diagnostic is done.

**Comment by mxsasha** [comment]
> sudo strace -p 11909
> strace: Process 11909 attached
> read(16,

Ok, so it's trying to read from file descriptor 16, and that call blocks. Can you share `lsof -n -p 11909` ? That should tell us more about the open file descriptors and might tell us more about what 16 is.

**Comment by rubenskuhl** [comment]
> > sudo strace -p 11909
> > strace: Process 11909 attached
> > read(16,
> 
> Ok, so it's trying to read from file descriptor 16, and that call blocks. Can you share `lsof -n -p 11909` ? That should tell us more about the open file descriptors and might tell us more about what 16 is.

It seems 16 is this one:

irrd-ROAI 11909 irrd   16u  IPv6             163697      0t0     TCP [2804:890:0:102::102]:50026->[2001:418:3ff::ffff:248]:https (ESTABLISHED)

**Comment by rubenskuhl** [comment]
Just out of curiosity, I tried this and could fetch the ROA feed:

curl -O https://rpki.gin.ntt.net/api/export.json
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 20.6M  100 20.6M    0     0  6165k      0  0:00:03  0:00:03 --:--:-- 6163k

**Comment by mxsasha** [comment]
The read should have timed out. I will have a closer look at the code for this regarding timeouts. I don't think we can extract further useful info from this process, so feel free to go ahead and kill the process. The next run of the scheduler (15 seconds) after that should start a new RPKI importer, and if this is indeed just a broken timeout, I expect that one to run normally.

**Comment by rubenskuhl** [comment]
RPKI import and validation completed after killing the old process, so everything fine for the time being.
