### ISSUE TITLE
Users can create infinite mail loops by choosing the RPSL submit address as its notify address

### ISSUE THREAD

**Issue by rubenskuhl** [irrdnet/irrd#518]
**Is your feature request related to a problem? Please describe.**
Nothing in IRRd prevents an user from choosing the RPSL submit address as an object notify address. So all it's needed to create an infinite mail loop is to change an object notify address to the RPSL submit address, and then submit an update. This will trigger the infinite loop chain. 

**Describe the solution you'd like**
I believe the best solution to be a set of addresses that can't be used as notify addresses. Documentation could suggest irrd@example.com and auto-dbm@example.com as likely candidates. Note that this would apply to both HTTP and mail submission vectors. 

**Describe alternatives you've considered**
- Something in the subject or body that would signal this as an RPSL submit response that shouldn't be processed as RPSL submit
- A domain wide block of notify addresses (like example.com)

**Additional context**
This issue already happened in a 4.2.0b1 deployment, triggering an 80k e-mails avalanche. But I don't consider that to be a bug, which is why this was created under feature request.

**Comment by mxsasha** [comment]
If I understand you right, the email avalanche is caused by IRRd sending a notification to itself, to which it replies about a parsing or authentication failure, which triggers another reply to itself? Bit confused on what the steps are here to cause the avalanche.

Blocking certain notification addresses is an option, but it's not my first choice because it depends on an admin to configure this and keep it up to date. Perhaps there is a nicer way to solve this without extra work for the admin, so I'd like to understand the avalanche a bit more.

**Comment by rubenskuhl** [comment]
```
Subject: FAILED: Notification of TC database changes


> Message-ID: <20210710232930.443532C02F1@bgp.net.br>
> From: db-admin@bgp.net.br
> Date: Sat, 10 Jul 2021 23:29:30 +0000 (UTC)
> Subject: Notification of TC database changes


SUMMARY OF UPDATE:

Number of objects found:                   12
Number of objects processed successfully:   0
    Create:        0
    Modify:        0
    Delete:        0
Number of objects processed with errors:   12
    Create:        0
    Modify:        1
    Delete:        0

DETAILED EXPLANATION:

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
---
Request FAILED: [(unreadable object class)] (unreadable object key)


You may receive this message because you are listed in
the notify attribute on the changed object(s), or because
you are listed in the mnt-nfy or upd-to attribute on a maintainer
of the object(s).

ERROR: unknown object class: You may receive this message because you are listed in
the notify attribute on the changed object(s), or because
you are listed in the mnt-nfy or upd-to attribute on a maintainer
of the object(s).

---
Request FAILED: [(unreadable object class)] (unreadable object key)

This message is auto-generated.
The request was made by email, with the following details:

ERROR: unknown object class: This message is auto-generated.
The request was made by email, with the following details

---
Request FAILED: [(unreadable object class)] (unreadable object key)

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Some objects in which you are referenced were requested
to be created, deleted or changed, but *failed* the 
proper authorisation for any of the referenced maintainers.

ERROR: unknown object class: ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Some objects in which you are referenced were requested
to be created, deleted or changed, but *failed* the 
proper authorisation for any of the referenced maintainers.

---
Request FAILED: [(unreadable object class)] (unreadable object key)

---
Modify FAILED AUTHORISATION for object below: [as-set] AS-nnnnnn:AS-CUSTOMERS:

ERROR: unknown object class: ---
Modify FAILED AUTHORISATION for object below

---
Request FAILED: [(unreadable object class)] (unreadable object key)

@@ -1,5 +1,5 @@
 as-set:         AS-nnnnnn:AS-CUSTOMERS
-descr:          AS-SET OF ASnnnnnn
+descr:          AS-SET OF nnnnnn
 members:        ASnnnnnn
 members:        ASmmmmmm
 admin-c:        xxxxxxx-NICBR
@@ -8,4 +8,3 @@
 mnt-by:         MAINT-ASnnnn
 changed:        [removed]@[removed].com.br 20210709
 source:         TC
-last-modified:  2021-07-10T00:48:29Z

ERROR: unknown object class: @@ -1,5 +1,5 @@
 as-set

---
Request FAILED: [(unreadable object class)] (unreadable object key)

*Rejected* new version of this object:

ERROR: unknown object class: *Rejected* new version of this object

---
Modify FAILED: [as-set] AS-nnnnn:AS-CUSTOMERS

as-set:         AS-nnnnnn:AS-CUSTOMERS
descr:          AS-SET OF nnnnnn
members:        ASnnnnnn
members:        ASmmmmmm

admin-c:        xxxxxx-NICBR
tech-c:         xxxxxx-NICBR
notify:         auto-dbm@bgp.net.br
mnt-by:         MAINT-ASnnnnnnn
changed:        [removed]@[removed].com.br 20210709
source:         TC

ERROR: Authorisation for as-set AS-nnnnnn:AS-CUSTOMERS failed: must by authenticated by one of: MAINT-ASnnnnnn

---
Request FAILED: [(unreadable object class)] (unreadable object key)

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

ERROR: unknown object class: ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

---
Request FAILED: [(unreadable object class)] (unreadable object key)

TC Internet Routing Registry

ERROR: unknown object class: TC Internet Routing Registry

---
Request FAILED: [(unreadable object class)] (unreadable object key)

Generated by IRRd version 4.2.0b1 on bgp.net.br

ERROR: unknown object class: Generated by IRRd version 4.2.0b1 on bgp.net.br

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by rubenskuhl** [comment]
It requires 2 steps:
1) Change the notification contact on an object to be the RPSL submit address (usually auto-dbm@ for most IRR deployments)
2) Make a change to that object that triggers a notification

**Comment by mxsasha** [comment]
It seems the issue is more that the from email address for IRRd mails should be some kind of noreply address? Or at least, not the IRRd submission address.

If email.from is set to the IRRd submission address, this also means any bounces will end up being treated as new IRRd submissions, triggering another response from IRRd. Not great, even if it does not result in a loop in that case. So I think the answer is in setting email.from to something different from IRRd's submission address, rather than restricting outgoing mails. I can add that to the docs. We could try to detect this situation, but it's not a very practical method.

**Comment by rubenskuhl** [comment]
The email.from is not set to the IRRd submission address:
```    email:
        footer: 'TC Internet Routing Registry'
        from: db-admin@bgp.net.br
        smtp: localhost```



So any e-mail configured can trigger the mail loop.

**Comment by mxsasha** [comment]
And db-admin@bgp.net.br is not the submission address for IRRd? Then I don't see how it could be a loop. Consider these two cases.

If auto-dbm@example.net is the IRRd submission address, and is set as the email.from address:

- User sets notification contact to auto-dbm@example.net
- Object is modified causing a notification to be sent to auto-dbm@example.net
- IRRd receives that notification as a submission, but it is not a valid object update, therefore IRRd will reply to the sender of the email, auto-dbm@example.net, with a failure. No other notifications are sent.
- The failure message is again received by IRRd as a submission, is also not valid, therefore IRRd will reply to the sender, auto-dbm@example.net, with a failure
- And so on

If email.from is set to noreply@example.com instead:
- User sets notification contact to auto-dbm@example.net
- Object is modified causing a notification to be sent to auto-dbm@example.net
- IRRd receives that notification as a submission, but it is not a valid object update, therefore IRRd will reply to the sender of the email, noreply@example.net, with a failure. No other notifications are sent.
- No loop occurs

**Comment by mxsasha** [comment]
@rubenskuhl any more thoughts on this?

**Comment by rubenskuhl** [comment]
> @rubenskuhl any more thoughts on this?

While your reasoning makes sense, the fact is that it happened... can we send logs via private e-mail ?

**Comment by mxsasha** [comment]
> > @rubenskuhl any more thoughts on this?
> 
> While your reasoning makes sense, the fact is that it happened... can we send logs via private e-mail ?

Sure, my email address is in my GitHub profile.

**Comment by mxsasha** [comment]
I didn't hear back, so I'm closing this for now.
