### ISSUE TITLE
Add bcrypt password hash algorithm

### ISSUE THREAD

**Issue by mxsasha** [irrdnet/irrd#573]
IRRD currently supports CRYPT and MD5 password hashes. Neither is very good for passwords. We should add a new more suitable hasher, possibly Argon2 or bcrypt. Merit is discussing internally what they see as the best choice.

**Comment by troy2914** [comment]
[Argon2](https://en.wikipedia.org/wiki/Argon2)
or
[Bcrypt](https://en.wikipedia.org/wiki/Bcrypt)

**Comment by mxsasha** [comment]
Merit also likes bcrypt, so that's what we're going for.
