### ISSUE TITLE
need to cleanup sockets for clients do not end cleanly.

### ISSUE THREAD

**Issue by troy2914** [irrdnet/irrd#607]
We had the situation where 68 workers were working on one ip.   Looking at netstat
it revealed that all 68 to that ip where in the state FIN_WAIT2.  To which the client should
have responded with FIN,ACK,  but apparently did not.

**Expected behaviour**
after 5 minutes in FIN_WAIT2 the socket should be force-ably cleaned up.

**IRRd version you are running**
IRRd -- version 4.1.8

**Comment by mxsasha** [comment]
Sounds good, will dig into it.

**Comment by mxsasha** [comment]
@troy2914 do you have some idea of how long these sockets were lingering? Are we talking an accumulation to 68 over a time frame of hours? More? A minute?

**Comment by mxsasha** [comment]
Initial thoughts: the close was initiated from IRRD, which is normal, but the remote end did not finish the closing of the socket, making the IRRD end stuck in FIN_WAIT2 ([state diagram](https://user-images.githubusercontent.com/2212681/105720101-5638f700-5f23-11eb-8985-528d667ef7ab.png)), waiting for a FIN from the remote end. It is possible that [this line](https://github.com/irrdnet/irrd/blob/main/irrd/server/whois/server.py#L163) ([docs for close()](https://docs.python.org/3/library/socket.html#socket.socket.close), [docs for shutdown()](https://docs.python.org/3/library/socket.html#socket.socket.shutdown)) blocks at this point. If the IRRD server process is blocked, the socket is still attached, preventing the kernel from cleaning it up even after tcp_fin_timeout.

Possible solution: set a timeout on the socket, which apparently we don't do at all in the whois TCP server. Would need a bit of testing though.

**Comment by mxsasha** [comment]
I haven't really been able to reproduce this, so I'm planning to move forward with settimeout on the socket. It definitely seems to need a highly rare kind of misbehaving client/OS/network.
