### ISSUE TITLE
delete doing strict checking when not required

### ISSUE THREAD

**Issue by rubenskuhl** [irrdnet/irrd#647]
**Is your feature request related to a problem? Please describe.**
In order to delete objects, IRRd is checking whether the fields in the object have proper syntax. But legacy objects might not have, due to not following current syntax requirements. 

**Describe the solution you'd like**
On objects that are being deleted, only the primary key components should be checked. On a route(6) it's both prefix and origin, on aut-num is the AS. 

**Describe alternatives you've considered**
An alternative would to be remove those objects from the output prior to sending it to IRRd for deletion. 

**Additional context**
One such use was to refer whom to notify by handle instead of by email, but this can manifest at almost any field.

**Comment by mxsasha** [comment]
I agree. There is some support in the RPSL parser already, we use it for NRTM deletes which sometimes have incomplete objects.

**Comment by mxsasha** [comment]
This is more complicated than I thought, in part because the tests for this are kind of hairy. Will revisit with #412.

**Comment by mxsasha** [comment]
As you say, the workaround for now is to fix the object when submitting it for deletion - it does not need to match the existing object outside of the primary key, object class and source.

**Comment by schelcj** [comment]
This is proving to be a problem for us as well. Has there been any development on this recently?
