### ISSUE TITLE
Should RPSLGenericNameField validate against the original value?

### ISSUE THREAD

**Issue by briandfoy** [irrdnet/irrd#651]
I'm merely perusing the code and don't have an installation of it. While reading through RPSLGenericNameField, I saw that it's parser validated the uppercased value against a regex that looked for Latin letters, digits, underscore, and dash. Once it passes this validation, it uses the original value.

However, there is at least one character in Unicode that's outside the 7-bit ASCII range but capitalizes into the 7-bit ASCII range: U+00DF (LATIN SMALL LETTER SHARP S) becomes the two characters SS. 

This is what is in irrd/rpsl/fields.py in RPSLGenericNameField:
 
        if not re_generic_name.match(upper_value):

This means that you could potentially get an unwanted character even after validation because you use the original value instead of the one you actually checked. Perhaps it should match against the original value, since the pattern is already case-insensitive:

        if not re_generic_name.match(value):

**Comment by mxsasha** [comment]
Sounds like you're entirely right. Thanks for reporting, will fix this soon.
