### ISSUE TITLE
Journal Serial Expiration and Garbage Collection

### ISSUE THREAD

**Issue by ericparton** [irrdnet/irrd#691]
Would it be possible to add a feature that would periodically delete any NRTM transactions in the journal that occurred before a given period of time? We'd like to implement a policy where only NRTM serials from the last two weeks are available via IRRd.

**Comment by mxsasha** [comment]
Yes, this is definitely something we can do. Not too difficult either - the journal is not referenced from anywhere, just queried from.

One thing to keep in mind is that it is currently also the best place to track historical object changes. IRRD has it's own log file, but that does not log all versions of every object change. So for any kind of auditing, the journal is currently the only source in IRRD itself.

**Comment by ericparton** [comment]
Thanks, that's good to know. Our internal provisioning system does have it's own auditing capabilities, so we should be good to go on that front.
