### ISSUE TITLE
Make example config copyable without line numbers

### ISSUE THREAD

**Issue by forkwhilefork** [irrdnet/irrd#762]
Right now, the example config in the docs (https://irrd.readthedocs.io/en/stable/admins/configuration/#example-configuration-file) has line numbers that are selected with the rest of the text. Before I can start editing the example, I have to remove all the line numbers, which is tedious. It would be better if there were no line numbers, or if they were not selected with the config.

**Comment by mxsasha** [comment]
Yes, makes sense :)

**Comment by mxsasha** [comment]
Looks like a template update some time ago fixed this.
