### ISSUE TITLE
inet(6)num objects allowed at non-RIR/NIR databases

### ISSUE THREAD

**Issue by rubenskuhl** [irrdnet/irrd#767]
**Is your feature request related to a problem? Please describe.**
TC IRR received object insertions of inet(6)num records. A non-RIR/NIR database should not have such records. 

**Describe the solution you'd like**
Extend sources.{name}.object_class_filter to authoritative databases and validate submissions against such filter

**Describe alternatives you've considered**
We are considering adding object class analysis to our near-real-time and daily verification scripts. 

**Additional context**
None

**Comment by fischerdouglas** [comment]
I think this problem could be covered with this suggestion:
https://github.com/irrdnet/irrd/discussions/415

I'm not a programmer, but maybe with some examples I could adapt/increase to create a pseudo-source based on NRO-Stats.

**Comment by mxsasha** [comment]
> **Describe the solution you'd like** Extend sources.{name}.object_class_filter to authoritative databases and validate submissions against such filter

I like this idea. Seems like a good feature to have and not too complex.

**Comment by rubenskuhl** [comment]
Way to go, @mxsasha .

**Comment by mxsasha** [comment]
> Way to go, @mxsasha .

Actually, the patch was mostly by @Justin-APNIC :)

**Comment by rubenskuhl** [comment]
> > Way to go, @mxsasha .
> 
> Actually, the patch was mostly by @Justin-APNIC :)

So kudos to @Justin-APNIC then! ;-)
