### ISSUE TITLE
How to handle null max_serial_global in event stream?

### ISSUE THREAD

**Issue by lamehost** [irrdnet/irrd#794]
Dear IRRd4 community,

I am testing v4.3.0rc1 and I've noticed that, at least in some cases, event stream returns _null_ _max_serial_global_:
```
$ curl -qs http://localhost:8080/v1/event-stream/initial/ | grep max_serial_global | json_pp 
{
   "data_type" : "irrd_event_stream_initial_download",
   "generated_at" : "2023-05-30T09:01:28.887023",
   "generated_on" : "lab-irrd-7c499d5949-qpn22",
   "last_change_timestamp" : null,
   "max_serial_global" : null,
   "object_classes_filter" : [],
   "sources_filter" : []
}
```

[Documentation](https://github.com/irrdnet/irrd/blob/stable/4.3.x/docs/users/queries/event-stream.rst?plain=1#L65) does not explicitely tell what to do when it happens, but i believe it means no futher data is available through the websockets and thus that you can't start your client yet.

Is that right?

Thank you

**Comment by mxsasha** [comment]
Yes, it means there is nothing in the journal yet, i.e. no changes have taken place for that source, so they also do not have a timestamp or serial to be reported.

**Comment by lamehost** [comment]
Thanks
