### ISSUE TITLE
Add an option to filter child AS-SETs on recursive queries

### ISSUE THREAD

**Issue by jccardonar** [irrdnet/irrd#823]
**Is your feature request related to a problem? Please describe.**

Some AS-SETs are too large, they include almost all prefixes on the Internet. In some cases, this reflects the reality of the AS-SET (e.g. the AS-SET belongs to a TIER-1). In some others, this happens because an AS-SET under the customer cone includes a large AS-SET, even when it does not make sense (e.g. a middle or low size AS-SET including a TIER-1 AS-SET).

We would like then to have a way of filtering AS-SETs when recursively resolving an AS-SET. 

**Describe the solution you'd like**

The next is open for discussion, but it is one solution we have envisioned. 
We would like to add an option to exclude or filter "child" AS-SETs in "a" and "i" whois queries.  

The methodology for setting which AS-SETs to filter could be similar to how source lists are done. Let us assume the command is  f, then it could be something like:

`!f<excluded as-sets> ignores as-sets , e.g. !fAS-1,AS-2. In addition, !f-lc returns the filtered as-sets currently established. This persists across queries.`

This could be the functionality of the filter option. Let us assume we have this sort of dependency between AS-SETs

```
AS-1
 +-- AS-2
 |   +-- AS-2-1
 |   |   +-- ASN21
 |   |       +-- 192.0.0.1
 |   +-- AS-2-2
 |       +-- ASN22
 |       |   +-- 192.0.0.2
 |       +-- ASN666
 |           +-- 192.0.0.6
 +-- AS-3
     +-- ASN23
     |   +-- 192.0.0.3
     +-- ASN666
         +-- 192.0.0.6
```

Not applying any filter a query !aAS-1 should return 192.0.0.1, 192.0.0.2, 192.0.0.3, 192.0.0.6
Applying filter AS-2, a query !aAS-1 should return 192.0.0.3, 192.0.0.6
Applying filter AS-2-1, a query !aAS-1 should return 192.0.0.2, 192.0.0.3, 192.0.0.6
Applying filter AS-2-2, a query !aAS-1 should return 192.0.0.1, 192.0.0.3, 192.0.0.6
Applying filter AS-3, a query !aAS-1 should return 192.0.0.1, 192.0.0.2, 192.0.0.6
Applying a filter AS-X (i.e. other separated as-set), the query should return the same as the unfiltered one.

Applying filter AS-1 should return the unfiltered list 

**Describe alternatives you've considered**

Not using any recursive query and applying the filtering ourselves could be a solution, but it would be an inefficient one. 

**Additional context**
N/A

**Comment by mxsasha** [comment]
Yes, good idea, this will be part of #422 / #824
