### ISSUE TITLE
IRRd documentation format fails presentation with many browsers

### ISSUE THREAD

**Issue by dhutchin-ctl** [irrdnet/irrd#888]
**Describe the bug**
Chrome, Edge, Safari and maybe other browsers have difficulty correctly rendering: https://irrd.readthedocs.io/en/stable/

**To Reproduce**
Visit: https://irrd.readthedocs.io/en/stable/ and scroll to the bottom of the left column and try to click on "License".  Many browsers will not let you scroll to the bottom.  Firefox lets you, but only after rendering engine scrolls the document footer to the top of the screen.

**Expected behaviour**
Better rendering

**IRRd version you are running**
It does not matter, this is a documentation issue, not an IRRd V4 issue.

**Additional context**

**Comment by dhutchin-ctl** [comment]
I don't know if this is a problem with the stuff in irrd/docs, or something at readthedocs.io.  But I send people to the documentation every couple of weeks and it is very frustrating not to be able to render the items near the bottom of the left column.  I can "control + '-'" a bunch of times, but that seems like the wrong solution.  If the problem is with readthedocs.io, then we need to get a ticket filed with them.  Not being familiar with how readthedocs works, or IRRd's use of it, I don't think I should be the one to file a bug report at https://github.com/readthedocs/readthedocs.org/issues

**Comment by mxsasha** [comment]
It's a problem with the sphinx theme used to render the doc: https://github.com/irrdnet/irrd/blob/main/docs/conf.py#L92

I had noticed it being a bit funky, didn't know it was this annoying in some browsers.
