### ISSUE TITLE
mntner with legacy auth can't be deleted 

### ISSUE THREAD

**Issue by rubenskuhl** [irrdnet/irrd#909]
**Describe the bug**
A mntner with a method supported only for legacy authentication (like CRYPT-PW) can't be removed

**To Reproduce**
Have a previous object with CRYPT-PW, try deleting it. 
ERROR: Invalid auth attribute: CRYPT-PW DummyValue: supported options are MD5-PW, BCRYPT-PW, PGPKEY-xxxxxxxx and IRRD-INTERNAL-AUTH for migrated objects

**Expected behaviour**
Deleting should care only about primary keys. The object should be removed. 

**IRRd version you are running**
4.4.3

**Additional context**
This was probably introduced either by the code that enables legacy authentication in 4.4 mainline or the fix in 4.4.3

**Comment by mxsasha** [comment]
I agree this should work. This is a more specific duplicate of #647

**Comment by rubenskuhl** [comment]
> I agree this should work. This is a more specific duplicate of #647

I think solving #647 would solve this one, but they are different since this was introduced alongside the concept of phasing out legacy authentication methods.  So I don't know which way you prefer handling it. 

Also different is that auth is a required field in mntner objects... so the workaround is different from the other fields from #647. For those, omitting the field works better; for auth, it needs to be replaced with a currently valid for new passwords auth scheme.
