### ISSUE TITLE
/ui/rpsl/update/  should support PGP updates just like email does.

### ISSUE THREAD

**Issue by troy2914** [irrdnet/irrd#949]
just like with ripe i can do:
curl --data-urlencode DATA@ripe.asc https://syncupdates.db.ripe.net/
I want to be able to do 
curl --data-urlencode DATA@nttcom.asc https://rr.ntt.net/ui/rpsl/update/

**Comment by mxsasha** [comment]
Could you give me a more complete example of how this now works with RIPE syncupdates? I can't get it to work - sending the inline PGP signed message in the DATA attribute just results in:

```
The following paragraph(s) do not look like objects
and were NOT PROCESSED:

-----BEGIN PGP SIGNED MESSAGE-----
...
```

**Comment by troy2914** [comment]
where the file containing the object is called "ripe"
`gpg -u $KEY --clearsign ripe`
then
`curl --data-urlencode DATA@ripe.asc https://syncupdates.db.ripe.net`

**Comment by troy2914** [comment]
btw, the asc file does start with the BEGIN PGP SIGNED MESSAGE,
and it does not seen to issue a an email to the summitter.   But the notification email goes out,  and the curl returns what I call `# this is noisy, but whatever`
